# Generated by Django 3.1.5 on 2021-02-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_modification', models.DateField()),
                ('date_add', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='productStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store', verbose_name='Product store')),
            ],
        ),
    ]
