# Generated by Django 3.1.5 on 2021-02-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210215_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='RecieveCard_number',
            field=models.CharField(default='9222081700188054728', max_length=19, verbose_name='Card Number'),
            preserve_default=False,
        ),
    ]
