# Generated by Django 3.1.5 on 2021-02-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_usercloses'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercloses',
            managers=[
            ],
        ),
    ]
