# Generated by Django 3.1.5 on 2021-02-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order1',
        ),
    ]
