# Generated by Django 3.1.5 on 2021-02-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_delete_order1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='SUDAN', max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_modification',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='card to card', max_length=50, verbose_name='Payment Method'),
        ),
    ]
